// <auto-generated />
using Kiemtra90;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kiemtra90.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("Kiemtra90.Model.Hanghoa", b =>
                {
                    b.Property<int>("HH_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("HH_GIABAN")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HH_GIANHAP")
                        .HasColumnType("TEXT");

                    b.Property<string>("HH_MA")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("HH_NHH_ID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HH_TEN")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("HH_ID");

                    b.ToTable("Hanghoa");
                });

            modelBuilder.Entity("Kiemtra90.Model.Nhomhanghoa", b =>
                {
                    b.Property<int>("NHH_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NHH_Ma")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NHH_Ten")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("NHH_ID");

                    b.ToTable("Nhomhanghoa");
                });
#pragma warning restore 612, 618
        }
    }
}
